default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  password: rails
  username: rails
  port: 5434

development:
  <<: *default
  database: loyalty_program_development

test:
  <<: *default
  database: loyalty_program_test

production:
  <<: *default
  database: loyalty_program_production
